---
---
language: python
services: docker

env:
  global:
    - ROLE_NAME: first5user
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/

# yamllint disable rule:line-length
notifications:
  slack:
    secure: YWeOcfHylg3TwNoc8fnqeGf8J9jl5D3QbFWrMbFHgY61J/qOyCp/nLVQfEyVFIWdEgS8MsmDGP72CnUCGEw4Yb0g9eVWxbyrbweuOgCBrQxqF56mpaJGxexu9iu0FbdJXAjmi6iDvw/RWj9xAUysGowF3NneeH9Yi+ygFgjEI+/3+DBX4fi5qRWuwLqAfUUc+VIloK+MLNe8reqXonoT0p8swuHDfA5LYRl2mwpjHPlTa0GdKYOc7qoRoY0RlTcT2s7iCptDhI/AFylQWvJzk13EvSKI8eAcF8DHL02QV6UOQVKfHYYyY4HA7o3eO7X3RT9AZFccWbjwwhmsgClr2CAoOj+60HMCCCQuTcDQlxFP571EaKyNAb6Wctyce0pAauM9na+YdnjLkWVn8VnxzdfdhP/JSncPG80B9iombLGgiFwWAaoSJip3NY2IVSjRVX2Ck/Otm0+dzeX9GJ5LhywRbkGDRWew7AEa5RmRaVezDSrn4ydxZ05+KOCHKY++3PwnscuP0gUQhlZtKuj5fceebqVYOTmggdtbla0XinXSfxayHSKurI470ZcE5Jqeu6twukepAdpe92SDeH2ACvOEUDPcQ+AJ8/FEYXFaFq7g/QFnwwCZlZI36Aops+J7ObE8Mnq+V1YkiJvSXVgklyWqP2awZOls1Zs/k1fOpmc=
# yamllint enable rule:line-length
