---
# NOT TESTED YET

- name: Add users | create users, shell, home dirs
  user:
    name: "{{ item.username }}"
    password: "{{ first5user_ansible_password }}"
    # generate new password
    createhome: yes
    append: yes
    group: "{{ item.main_group }}"
    groups: "{{ item.groups | join(',') }}"
    shell: "{{ first5user_default_shell }}"
    generate_ssh_key: no
    update_password: on_create
    comment: 'created by ansible'
  with_items: '{{first5user_ssh_users}}'



- name: Setup | authorized key upload
  authorized_key:
    user:  "{{ item.username }}"
    key: "{{ lookup('file', item.key) }}"
    state: "{{ item.state | default('present')}}"
  with_items: '{{ first5user_ssh_users}}'
  become: true
  tags: [user_ssh_keys]


- name: Sudoers | update sudoers file and validate
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.username }}'
    line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    validate: 'visudo -cf %s'
    insertafter: EOF
  with_items: '{{first5user_ssh_users}}'
  when: item.use_sudo == True

# - name: Add Ansible user to the passwordless sudoers.
#   lineinfile: >
#     dest=/etc/sudoers
#     regexp='^{{ first5user_ansible_username }}'
#     line='{{ first5user_ansible_username }} ALL=(ALL) NOPASSWD: ALL'
#     state=present
#     validate='visudo -cf %s'




- name: Add other users to the sudoers not requiring tty.
  lineinfile:
    dest: /etc/sudoers
    regexp: "^Defaults{{ first5user_ansible_username }}"
    line: "Defaults:{{ item.username }}  !requiretty"
    state: present
    validate: 'visudo -cf %s'
  with_items: '{{first5user_ssh_users}}'
