---

- name: Change root password
  user:
    name: root
    password: "{{ first5user_root_password }}"
  when: first5user_changerootpwd


- name: Add/remove required groups
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ first5user_ansible_groups }}"
    - "{{ first5user_ansible_add_groups | default([]) }}"

- name: Install sudo package | Debian
  apt:
    name: sudo
  when: ansible_os_family == 'Debian'

- name: Install sudo package | RedHat
  yum:
    name: sudo
  when: ansible_os_family == 'RedHat'


- name: common | configure prompt
  lineinfile: dest=/etc/bash.bashrc regexp="^PS1=" line="PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'" backup=yes
  sudo: true
  tags: common
  when: ansible_os_family == 'Debian'

- name: common | copy bash config files
  template:
    src: bashrc_skel.j2
    dest: /etc/skel/.bashrc
    backup: yes
  tags: common
  when: ansible_os_family == 'Debian'

# TODO: Make idempotent
# Also may best set shell to sh as low resource use and basic for ansible
# temp removed groups as not idempotent and not needed as group

- name: Add ansible user
  user:
    name: "{{ first5user_ansible_username }}"
    password: "{{ first5user_ansible_password }}"
    append: "{{ first5user_append_groups }}"
    group: "{{ first5user_admin_group }}"
    groups: "{{ first5user_ansible_user_groups | join(',') }}"
    shell: "{{ first5user_default_shell }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    update_password: on_create

- name: Set up authorized_keys for the ansible user
  authorized_key:
    user: "{{ first5user_ansible_username }}"
    key: "{{ lookup('file', item) }}"
  with_items: first5user_public_ssh_keys
  sudo: true

- name: create users ssh directory
  file:
    path: "/home/{{ item.user }}/.ssh"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ first5user_admin_group }}"
    mode: 0700
    recurse: no
  with_items:
    - "{{first5deploy_user_keys}}"
    - "{{first5deploy_user_private_keys}}"
  sudo: true

- name: Put public keys in place for users
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ item.user }}/.ssh/{{ item.dest }}"
    mode: "{{ item.mode|default('0600') }}"
    owner: "{{ item.user }}"
    group: "{{ first5user_admin_group }}"
  with_items: first5deploy_user_keys

# this is for when you have encrypted id_rsa keys in your repo
- name: Put private keys in place for users
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ item.user }}/.ssh/{{ item.dest }}"
    mode: "{{ item.mode|default('0600') }}"
    owner: "{{ item.user }}"
    group: "{{ first5user_admin_group }}"
  with_items: first5deploy_user_private_keys


- name: Decrypt the private key
  command: openssl aes-256-cbc -salt -a -d -in /home/{{ item.user }}/.ssh/{{ item.dest }}
           -out /home/{{ item.user }}/.ssh/{{ item.dest }}-decrypted.key -k {{ ssh_key_password }}
           creates=/home/{{ item.user }}/.ssh/{{ item.dest }}-decrypted.key
  with_items: first5deploy_user_private_keys

- name: Rename the decrypted private key
  command: mv /home/{{ item.user }}/.ssh/{{ item.dest }}-decrypted.key /home/{{ item.user }}/.ssh/{{ item.dest }}
           removes=/home/{{ item.user }}/.ssh/{{ item.dest }}-decrypted.key
  with_items: first5deploy_user_private_keys

- name: Restore permissions on key files
  file:
    path: "/home/{{ item.user }}/.ssh/{{ item.dest }}"
    owner: "{{ item.user }}"
    group: "{{ first5user_admin_group }}"
    mode: "{{ item.mode|default('0600') }}"
  changed_when: False
  with_items: first5deploy_user_private_keys
  sudo: true

- name: Setup vagrant user for ssh if local
  user:
    name: vagrant
    shell: /bin/bash
    group: "{{ first5user_admin_group }}"
    append: yes
  when: inventory_hostname in groups['local']


- name: Add Ansible user to the passwordless sudoers.
  lineinfile: >
    dest=/etc/sudoers
    regexp='^{{ first5user_ansible_username }}'
    line='{{ first5user_ansible_username }} ALL=(ALL) NOPASSWD: ALL'
    state=present
    validate='visudo -cf %s'

- name: Add Ansible user to the sudoers not requiring tty.
  lineinfile: >
    dest=/etc/sudoers
    insertafter="^Defaults    requiretty"
    line='Defaults:{{ first5user_ansible_username }}  !requiretty'
    state=present
    validate='visudo -cf %s'

- name: Record that we have already run User setup for this host
  set_fact:
    first5user_ran: true